-- POLARIS 직업 설명 수정 (커리어넷 잘린 설명 → 직접 작성 설명으로 교체)
-- Supabase SQL Editor에 붙여넣기하여 실행

UPDATE jobs SET description = 'AI 알고리즘을 설계·개발하고 실제 서비스에 적용하는 소프트웨어 전문가' WHERE name = 'AI 개발자';
UPDATE jobs SET description = '대규모 데이터에서 패턴을 발견하고 비즈니스 인사이트를 도출하는 전문가' WHERE name = '데이터 과학자';
UPDATE jobs SET description = '기계가 스스로 학습하는 AI 모델을 설계·개발·배포하는 엔지니어' WHERE name = '머신러닝 엔지니어';
UPDATE jobs SET description = '로봇 시스템의 하드웨어와 소프트웨어를 연구·개발하는 공학 전문가' WHERE name = '로봇공학자';
UPDATE jobs SET description = '양자역학 원리를 활용한 차세대 컴퓨터를 연구하는 과학자' WHERE name = '양자컴퓨터 연구원';
UPDATE jobs SET description = '해킹·사이버 공격으로부터 시스템과 데이터를 보호하는 보안 전문가' WHERE name = '사이버 보안 전문가';
UPDATE jobs SET description = '탈중앙화 분산 원장 기술을 활용한 서비스를 개발하는 엔지니어' WHERE name = '블록체인 개발자';
UPDATE jobs SET description = '반도체 소자·공정을 연구하고 차세대 칩 기술을 개발하는 전문가' WHERE name = '반도체 연구원';
UPDATE jobs SET description = '뇌와 신경계의 구조·기능을 연구하는 신경과학 전문가' WHERE name = '뇌과학자(신경과학자)';
UPDATE jobs SET description = '생명체의 원리를 이용해 신약·식품·환경 기술을 개발하는 연구자' WHERE name = '생명공학자';
UPDATE jobs SET description = 'DNA를 조작해 질병 치료·농작물 개량 등의 연구를 수행하는 과학자' WHERE name = '유전공학자';
UPDATE jobs SET description = '질병의 원인과 치료법을 연구하는 의과학자' WHERE name = '의학 연구원';
UPDATE jobs SET description = '신약 후보물질을 발견하고 효능·안전성을 검증하는 연구자' WHERE name = '제약 연구원';
UPDATE jobs SET description = '신약·의료기기의 인체 적용 시험을 기획·관리하는 전문가' WHERE name = '임상시험 전문가';
UPDATE jobs SET description = '자연현상의 원리를 탐구하고 새로운 지식을 창출하는 연구자' WHERE name = '과학 연구원';
UPDATE jobs SET description = '물질과 에너지의 기본 법칙을 연구하는 자연과학자' WHERE name = '물리학자';
UPDATE jobs SET description = '물질의 성질·반응을 연구하고 신소재·물질을 개발하는 과학자' WHERE name = '화학자';
UPDATE jobs SET description = '수리 이론과 알고리즘을 연구하며 다양한 분야에 응용하는 전문가' WHERE name = '수학자';
UPDATE jobs SET description = '우주의 천체와 현상을 관측·분석하는 우주과학 전문가' WHERE name = '천문학자';
UPDATE jobs SET description = '바다의 물리·화학·생물·지질 현상을 연구하는 해양과학자' WHERE name = '해양학자';
UPDATE jobs SET description = '대기 현상을 연구하고 날씨를 예측하는 대기과학 전문가' WHERE name = '기상학자';
UPDATE jobs SET description = '환경 오염 문제를 해결하는 기술을 연구·개발하는 엔지니어' WHERE name = '환경 공학자';
UPDATE jobs SET description = '유적·유물을 발굴·분석하여 과거 인류 역사를 연구하는 학자' WHERE name = '고고학자';
UPDATE jobs SET description = '과거 사건과 문화를 연구하고 해석하는 인문학자' WHERE name = '역사학자';
UPDATE jobs SET description = '인류의 문화·사회·진화를 연구하는 학자' WHERE name = '인류학자';
UPDATE jobs SET description = '사회 구조·집단 행동·사회 변화를 연구하는 학자' WHERE name = '사회학자';
UPDATE jobs SET description = '인간·존재·지식·윤리의 근본 문제를 탐구하는 학자' WHERE name = '철학자';
UPDATE jobs SET description = '경제 현상과 정책 효과를 분석하는 전문 연구자' WHERE name = '경제 연구원';
UPDATE jobs SET description = '심리학과 경제학을 결합해 인간의 경제적 의사결정을 연구하는 학자' WHERE name = '행동경제학자';
UPDATE jobs SET description = '정부 정책의 효과를 분석하고 대안을 제시하는 전문가' WHERE name = '정책 분석가';
UPDATE jobs SET description = '소비자 동향과 시장 데이터를 분석해 비즈니스 전략을 지원하는 전문가' WHERE name = '시장 조사 분석가';
UPDATE jobs SET description = '비즈니스 데이터를 분석해 의사결정을 지원하는 전문가' WHERE name = '데이터 분석가';
UPDATE jobs SET description = '정보를 안전하게 보호하는 암호 이론과 알고리즘을 연구하는 전문가' WHERE name = '암호학자';
UPDATE jobs SET description = '범죄자의 심리와 행동 패턴을 분석해 수사를 지원하는 전문가' WHERE name = '범죄 심리 분석관(프로파일러)';
UPDATE jobs SET description = '과학적 방법으로 범죄 증거를 수집·분석하는 과학수사 전문가' WHERE name = '법과학자';
UPDATE jobs SET description = '복잡한 과학 연구를 일반 대중이 이해할 수 있도록 전달하는 언론인' WHERE name = '과학 저널리스트';
UPDATE jobs SET description = '사실에 기반한 다큐멘터리 프로그램을 기획·제작하는 방송 프로듀서' WHERE name = '다큐멘터리 PD';
UPDATE jobs SET description = '기술·사회 트렌드를 분석해 미래를 예측하고 시나리오를 제시하는 전문가' WHERE name = '미래학자';
UPDATE jobs SET description = '기술·특허·지식재산의 경제적 가치를 분석·평가하는 전문가' WHERE name = '기술 가치 평가사';
UPDATE jobs SET description = '발명의 신규성·진보성을 심사하고 특허 권리를 판단하는 공무원' WHERE name = '특허 심사관';
UPDATE jobs SET description = '소프트웨어를 설계·개발·테스트·유지보수하는 개발 전문가' WHERE name = '소프트웨어 엔지니어';
UPDATE jobs SET description = '서버·네트워크·인프라를 설계하고 안정적으로 운영하는 전문가' WHERE name = '시스템 엔지니어';
UPDATE jobs SET description = '클라우드 기반 인프라와 서비스 구조를 설계하는 IT 전문가' WHERE name = '클라우드 아키텍트';
UPDATE jobs SET description = '개발과 운영을 통합해 빠르고 안정적인 소프트웨어 배포를 담당하는 전문가' WHERE name = 'DevOps 엔지니어';
UPDATE jobs SET description = '프로젝트의 일정·범위·예산·품질을 종합적으로 관리하는 전문가' WHERE name = '프로젝트 매니저(PM)';
UPDATE jobs SET description = '데이터베이스 시스템을 설계·운영·최적화하는 전문가' WHERE name = '데이터베이스 관리자';
UPDATE jobs SET description = '기업의 정보 자산을 위협으로부터 보호하는 보안 전문가' WHERE name = '정보 보안 엔지니어';
UPDATE jobs SET description = '건물의 공간·구조·미를 설계하고 시공을 감리하는 전문가' WHERE name = '건축가';
UPDATE jobs SET description = '도로·교량·댐 등 사회 기반 시설을 설계·시공하는 엔지니어' WHERE name = '토목 공학자';
UPDATE jobs SET description = '전기 설비를 설계·시공·점검하는 전기 기술 전문가' WHERE name = '전기 기사';
UPDATE jobs SET description = '칩의 회로 구조를 설계하는 반도체 전문 엔지니어' WHERE name = '반도체 설계자';
UPDATE jobs SET description = '토지 이용·교통·환경을 고려해 도시 발전 계획을 수립하는 전문가' WHERE name = '도시 계획가';
UPDATE jobs SET description = '기업의 재무 상태를 기록·분석·보고하고 감사하는 공인 전문가' WHERE name = '회계사';
UPDATE jobs SET description = '세금 신고·납부·절세 전략을 지원하는 세무 전문가' WHERE name = '세무사';
UPDATE jobs SET description = '보험·연금의 위험과 비용을 수리적으로 분석하는 전문가' WHERE name = '보험 계리사';
UPDATE jobs SET description = '기업·개인의 신용도와 채무 상환 능력을 평가하는 금융 전문가' WHERE name = '신용 분석가';
UPDATE jobs SET description = '기업이 직면하는 다양한 위험을 식별·평가·관리하는 전문가' WHERE name = '리스크 관리자';
UPDATE jobs SET description = '기업의 재무 계획·예산·원가를 관리하는 재무 총괄 전문가' WHERE name = '금융 컨트롤러';
UPDATE jobs SET description = '데이터를 수집·분석하고 수학적 모델로 현상을 설명하는 전문가' WHERE name = '통계학자';
UPDATE jobs SET description = '법정에서 사건을 심리하고 법률에 따라 판결을 내리는 사법부 공무원' WHERE name = '법관(판사)';
UPDATE jobs SET description = '범죄를 수사하고 형사 소송을 제기·수행하는 법무부 소속 공무원' WHERE name = '검사';
UPDATE jobs SET description = '법적 분쟁에서 의뢰인을 대리하고 법률 자문을 제공하는 전문가' WHERE name = '변호사';
UPDATE jobs SET description = '특허·상표·디자인권 등 지식재산권 출원·등록을 대리하는 전문가' WHERE name = '변리사';
UPDATE jobs SET description = '법원·등기소 제출 서류 작성·제출을 대행하는 법률 보조 전문가' WHERE name = '법무사';
UPDATE jobs SET description = '항공기의 안전 운항을 위해 기체·엔진·장비를 점검·정비하는 전문가' WHERE name = '항공기 정비사';
UPDATE jobs SET description = '항공기의 이착륙과 비행 경로를 지시하여 안전한 항공 교통을 관리하는 공무원' WHERE name = '항공 관제사';
UPDATE jobs SET description = '상품의 생산·보관·운송·배달 전 과정을 효율적으로 관리하는 전문가' WHERE name = '물류 전문가';
UPDATE jobs SET description = '제품 생산 과정과 작업 방식을 최적화하는 생산 엔지니어' WHERE name = '공정 설계자';
UPDATE jobs SET description = '제품·서비스가 정해진 기준을 충족하는지 검사·관리하는 전문가' WHERE name = '품질 관리원';
UPDATE jobs SET description = '효율적인 생산 일정과 자원 배분을 계획하는 전문가' WHERE name = '생산 계획 전문가';
UPDATE jobs SET description = '비즈니스 운영 데이터를 분석해 효율 개선 방안을 도출하는 전문가' WHERE name = '운영 분석가';
UPDATE jobs SET description = '의약품을 조제하고 약물 복용법을 안내하는 의료 전문가' WHERE name = '약사';
UPDATE jobs SET description = '환자의 의료 기록을 체계적으로 관리·분류·보관하는 전문가' WHERE name = '의무기록사';
UPDATE jobs SET description = '부동산·동산·기업 가치를 전문적으로 평가하는 자격사' WHERE name = '감정평가사';
UPDATE jobs SET description = '기업이나 기관의 재무·업무를 독립적으로 검토하는 전문가' WHERE name = '감사원';
UPDATE jobs SET description = '산업 현장의 사고 예방을 위한 안전 시스템을 관리하는 전문가' WHERE name = '안전 관리 기사';
UPDATE jobs SET description = '개발 사업이 환경에 미치는 영향을 조사·분석하는 전문가' WHERE name = '환경 영향 평가사';
UPDATE jobs SET description = '도서관 자료를 수집·분류·관리하고 이용자를 지원하는 전문가' WHERE name = '도서관 사서';
UPDATE jobs SET description = '공공·민간 기관의 기록을 체계적으로 보존·관리하는 전문가' WHERE name = '기록물 관리 전문가';
UPDATE jobs SET description = '조직의 행정 업무를 체계적으로 관리하고 운영하는 전문가' WHERE name = '행정 전문가';
UPDATE jobs SET description = '마음의 어려움을 겪는 사람과 대화로 심리적 회복을 돕는 전문가' WHERE name = '심리 상담가';
UPDATE jobs SET description = '심리 검사·진단·치료를 통해 정신건강 문제를 다루는 전문가' WHERE name = '임상 심리사';
UPDATE jobs SET description = '정신질환자와 가족의 사회복귀를 지원하는 복지 전문가' WHERE name = '정신건강 사회복지사';
UPDATE jobs SET description = '경제적·사회적 어려움을 겪는 사람들을 지원하는 복지 전문가' WHERE name = '사회복지사';
UPDATE jobs SET description = '환자의 건강을 돌보고 치료 과정을 보조하는 의료 전문가' WHERE name = '간호사';
UPDATE jobs SET description = '환자를 진찰·진단·치료하는 의료 전문가' WHERE name = '의사(소아과·정신건강의학과)';
UPDATE jobs SET description = '한방 의학으로 환자를 진찰·치료하는 의료 전문가' WHERE name = '한의사';
UPDATE jobs SET description = '구강 검진·스케일링·예방 처치를 수행하는 치과 의료 인력' WHERE name = '치과 위생사';
UPDATE jobs SET description = '동물의 질병을 진단·치료하고 공중보건을 관리하는 의료 전문가' WHERE name = '수의사';
UPDATE jobs SET description = '동물과의 상호작용을 활용해 사람의 심리·신체 회복을 돕는 치료사' WHERE name = '동물 매개 치료사';
UPDATE jobs SET description = '언어·발음·의사소통 장애를 진단하고 치료하는 전문가' WHERE name = '언어 치료사';
UPDATE jobs SET description = '신체·인지 장애인의 일상생활 능력 회복을 돕는 재활 전문가' WHERE name = '작업 치료사';
UPDATE jobs SET description = '운동·물리적 방법으로 신체 기능 회복을 돕는 재활 전문가' WHERE name = '물리 치료사';
UPDATE jobs SET description = '그림·조소 등 미술 활동으로 심리 치료를 진행하는 전문가' WHERE name = '미술 치료사';
UPDATE jobs SET description = '음악 활동을 통해 심리·신체·인지 문제를 치료하는 전문가' WHERE name = '음악 치료사';
UPDATE jobs SET description = '놀이를 매개로 아동의 심리 문제를 치료하는 전문가' WHERE name = '놀이 치료사';
UPDATE jobs SET description = '장애·부상·수술 후 환자의 기능 회복을 종합적으로 지원하는 전문가' WHERE name = '재활 전문가';
UPDATE jobs SET description = '영유아·아동의 발달을 평가하고 성장을 지원하는 전문가' WHERE name = '아동 발달 전문가';
UPDATE jobs SET description = '장애 학생의 특성에 맞는 교육을 제공하는 학교 교원' WHERE name = '특수 교사';
UPDATE jobs SET description = '유아의 놀이·학습·사회성 발달을 지원하는 교육 전문가' WHERE name = '유치원 교사';
UPDATE jobs SET description = '초등학생에게 기초 교과를 가르치고 생활 지도를 하는 교원' WHERE name = '초등학교 교사';
UPDATE jobs SET description = '학생의 적성·흥미를 파악하고 진로 설계를 돕는 교원' WHERE name = '진로 상담 교사';
UPDATE jobs SET description = '청소년의 건강한 성장과 자립을 지원하는 복지·교육 전문가' WHERE name = '청소년 지도사';
UPDATE jobs SET description = '노인의 복지 서비스를 계획·연계·관리하는 전문가' WHERE name = '노인 복지 코디네이터';
UPDATE jobs SET description = '거동이 불편한 노인·장애인의 일상생활을 돕는 돌봄 전문가' WHERE name = '요양 보호사';
UPDATE jobs SET description = '말기 환자와 가족이 존엄한 임종을 맞이하도록 돌봄을 관리하는 전문가' WHERE name = '호스피스 관리자';
UPDATE jobs SET description = '환자의 진료 일정·의료 서비스를 조율하고 접근성을 높이는 전문가' WHERE name = '헬스케어 코디네이터';
UPDATE jobs SET description = '병원에서 환자와 가족의 심리·경제·사회적 문제를 지원하는 복지 전문가' WHERE name = '의료 사회복지사';
UPDATE jobs SET description = '구직자의 취업 역량을 평가하고 적합한 일자리 연결을 지원하는 전문가' WHERE name = '직업 상담사';
UPDATE jobs SET description = '사회 문제 해결을 비즈니스 모델로 실현하는 혁신 창업가' WHERE name = '사회 기업가';
UPDATE jobs SET description = '공익을 위해 사회·환경·인권 분야에서 활동하는 전문가' WHERE name = '비영리 단체 활동가';
UPDATE jobs SET description = '인권 침해 사례를 법적으로 지원하고 제도 개선을 추구하는 변호사' WHERE name = '인권 변호사';
UPDATE jobs SET description = '이주민·다문화 가정의 사회 적응과 통합을 지원하는 전문가' WHERE name = '다문화 코디네이터';
UPDATE jobs SET description = '분쟁·재난 지역에서 인도주의적 지원 활동을 수행하는 전문가' WHERE name = '국제 구호 활동가';
UPDATE jobs SET description = '자원봉사 프로그램을 기획·운영하고 봉사자를 관리하는 전문가' WHERE name = '봉사 코디네이터';
UPDATE jobs SET description = '복지 제도의 효과를 분석하고 개선 방안을 연구하는 전문가' WHERE name = '복지 정책 연구원';
UPDATE jobs SET description = '자연·생태계 보호의 중요성을 교육하는 환경 교육 전문가' WHERE name = '생태 환경 교육사';
UPDATE jobs SET description = '지역 공동체 프로그램과 공간을 운영하며 사람들을 연결하는 전문가' WHERE name = '공동체 운영자';
UPDATE jobs SET description = '갈등 해결과 평화 문화 확산을 위한 교육을 진행하는 전문가' WHERE name = '평화 교육 활동가';
UPDATE jobs SET description = '새로운 나라에 정착하는 이민자의 생활 적응을 돕는 전문가' WHERE name = '이민자 지원 전문가';
UPDATE jobs SET description = '영상 콘텐츠를 기획·촬영·편집해 유튜브에 게시하며 구독자와 소통하는 창작자' WHERE name = '유튜버(크리에이터)';
UPDATE jobs SET description = '짧은 숏폼 영상을 제작해 SNS 플랫폼에서 영향력을 키우는 창작자' WHERE name = '틱톡·릴스 크리에이터';
UPDATE jobs SET description = '오디오 콘텐츠를 기획·녹음·배포하는 미디어 창작자' WHERE name = '팟캐스터';
UPDATE jobs SET description = '게임·토크 등 실시간 방송을 진행하며 시청자와 실시간 소통하는 창작자' WHERE name = '스트리머';
UPDATE jobs SET description = 'SNS 팔로워 영향력을 활용해 브랜드·제품을 홍보하는 전문가' WHERE name = '인플루언서 마케터';
UPDATE jobs SET description = '기업·브랜드의 SNS 채널을 운영하고 콘텐츠를 관리하는 전문가' WHERE name = '소셜 미디어 매니저';
UPDATE jobs SET description = '인터넷 연재 만화를 기획·그림·스토리로 제작하는 창작자' WHERE name = '웹툰 작가';
UPDATE jobs SET description = '허구의 이야기를 창작하고 출판하는 문학 창작자' WHERE name = '소설가';
UPDATE jobs SET description = '영화·드라마·애니메이션의 대본을 쓰는 전문 작가' WHERE name = '시나리오 작가';
UPDATE jobs SET description = 'TV·OTT 드라마의 대본을 집필하는 창작 전문가' WHERE name = '드라마 작가';
UPDATE jobs SET description = '게임의 세계관·시나리오·캐릭터 스토리를 창작하는 전문가' WHERE name = '게임 스토리 작가';
UPDATE jobs SET description = '광고·마케팅에 사용되는 설득력 있는 문구를 창작하는 전문가' WHERE name = '카피라이터';
UPDATE jobs SET description = 'TV·라디오 방송의 대본과 구성을 담당하는 전문가' WHERE name = '방송 작가';
UPDATE jobs SET description = '사건·현상을 취재하고 기사를 작성해 독자에게 전달하는 언론인' WHERE name = '기자';
UPDATE jobs SET description = '원고를 검토·수정·구성해 책으로 완성하는 출판 전문가' WHERE name = '편집자(출판)';
UPDATE jobs SET description = '영화의 전체 제작 과정을 총괄하고 연출하는 창작 지휘자' WHERE name = '영화 감독';
UPDATE jobs SET description = '음악에 맞는 영상을 기획·연출하는 영상 창작자' WHERE name = '뮤직비디오 감독';
UPDATE jobs SET description = '콘서트·뮤지컬·연극 등 공연을 기획·운영하는 전문가' WHERE name = '공연 기획자';
UPDATE jobs SET description = '연극·뮤지컬·무용 공연의 무대를 총괄 연출하는 예술가' WHERE name = '무대 연출가';
UPDATE jobs SET description = '연극·영화·드라마에서 캐릭터를 연기하는 퍼포밍 아티스트' WHERE name = '배우';
UPDATE jobs SET description = '노래·댄스·연기를 결합한 뮤지컬에 출연하는 공연 예술가' WHERE name = '뮤지컬 배우';
UPDATE jobs SET description = '음악을 창작·녹음·공연하며 청중과 감동을 나누는 예술가' WHERE name = '가수·음악 아티스트';
UPDATE jobs SET description = '음악 곡을 만들고 편곡하는 음악 창작 전문가' WHERE name = '작곡가';
UPDATE jobs SET description = '애니메이션·광고·오디오북 등에서 목소리로 연기하는 전문가' WHERE name = '성우';
UPDATE jobs SET description = '공연·뮤직비디오 등의 무용과 동작을 창작·지도하는 예술가' WHERE name = '안무가';
UPDATE jobs SET description = '사용자가 디지털 서비스를 편리하게 이용하도록 경험을 설계하는 전문가' WHERE name = 'UX 디자이너';
UPDATE jobs SET description = '기업·제품의 시각적 정체성(로고·컬러·타이포)을 설계하는 전문가' WHERE name = '브랜드 디자이너';
UPDATE jobs SET description = '영상에 움직이는 그래픽을 제작하는 디지털 디자이너' WHERE name = '모션 그래픽 디자이너';
UPDATE jobs SET description = '컴퓨터로 3D 모델·애니메이션을 제작하는 디지털 예술가' WHERE name = '3D 아티스트';
UPDATE jobs SET description = '책·광고·게임 등에 사용되는 그림을 그리는 창작 디자이너' WHERE name = '일러스트레이터';
UPDATE jobs SET description = '의류·액세서리를 기획하고 디자인하는 패션 전문가' WHERE name = '패션 디자이너';
UPDATE jobs SET description = '가전·가구·소비재 등의 형태와 기능을 디자인하는 전문가' WHERE name = '제품 디자이너';
UPDATE jobs SET description = '광고·영상·출판의 시각 방향성을 총괄 기획하는 크리에이티브 리더' WHERE name = '아트 디렉터';
UPDATE jobs SET description = '예술·광고·기록 등 다양한 목적으로 사진을 촬영하는 창작자' WHERE name = '사진작가';
UPDATE jobs SET description = '촬영된 영상 소재를 편집해 완성된 영상 콘텐츠로 만드는 전문가' WHERE name = '영상 편집자';
UPDATE jobs SET description = '미술관·박물관에서 전시를 기획하고 작품을 선정·해설하는 전문가' WHERE name = '전시 큐레이터';
UPDATE jobs SET description = '광고주와 광고대행사 사이에서 광고 캠페인을 기획·조율하는 전문가' WHERE name = '광고 AE';
UPDATE jobs SET description = '마케팅 캠페인에 필요한 시각 자료를 디자인하는 전문가' WHERE name = '마케팅 디자이너';
UPDATE jobs SET description = '향수·화장품·식품의 향기를 조합하고 개발하는 향기 전문가' WHERE name = '조향사';
UPDATE jobs SET description = '신체·행위 자체를 예술 표현 수단으로 삼는 현대 예술가' WHERE name = '퍼포먼스 아티스트';
UPDATE jobs SET description = '국가·지방자치단체에서 행정·복지 업무를 담당하는 국가 공무원' WHERE name = '공무원(행정직·복지직)';
UPDATE jobs SET description = '국가를 대표해 외국과의 관계를 유지·발전시키는 외무부 공무원' WHERE name = '외교관';
UPDATE jobs SET description = '범죄 예방·수사 및 질서 유지를 담당하는 국가 공무원' WHERE name = '경찰관';
UPDATE jobs SET description = '화재 진압·인명 구조·응급 처치를 담당하는 국가 공무원' WHERE name = '소방관';
UPDATE jobs SET description = '국가 안보를 담당하며 부대를 지휘하는 직업 군인' WHERE name = '군인(장교)';
UPDATE jobs SET description = '해양에서 범죄 단속·안전 관리·해양 재난 구조를 담당하는 공무원' WHERE name = '해경';
UPDATE jobs SET description = '응급 환자에게 즉각적인 처치를 제공하고 병원으로 이송하는 응급 전문가' WHERE name = '119 구급대원';
UPDATE jobs SET description = '교도소에서 수용자를 관리하고 교정·교화를 담당하는 법무부 공무원' WHERE name = '교도관';
UPDATE jobs SET description = '여객기·화물기를 안전하게 운항하는 조종 전문가' WHERE name = '항공기 조종사';
UPDATE jobs SET description = '기내에서 승객의 안전과 편의를 책임지는 항공 서비스 전문가' WHERE name = '승무원';
UPDATE jobs SET description = '호텔에서 객실·식음료·컨시어지 서비스를 제공하는 환대 전문가' WHERE name = '호텔리어';
UPDATE jobs SET description = '임원·관리자의 일정·업무·커뮤니케이션을 지원하는 전문 행정가' WHERE name = '비서';
UPDATE jobs SET description = '채용·교육·평가·보상 등 인력 관리 전반을 담당하는 전문가' WHERE name = '인사 관리자(HR)';
UPDATE jobs SET description = '사무환경·자산·행사·복리후생 등 회사 운영을 지원하는 전문가' WHERE name = '총무 담당자';
UPDATE jobs SET description = '기업 운영의 행정·재무·법무 등 지원 업무를 총괄하는 전문가' WHERE name = '경영 지원 전문가';
UPDATE jobs SET description = '팀의 목표 달성을 위해 인력·일정·성과를 관리하는 중간 관리자' WHERE name = '팀 매니저';
UPDATE jobs SET description = '조직의 일상적인 운영 프로세스와 자원을 효율적으로 관리하는 전문가' WHERE name = '운영 관리자';
UPDATE jobs SET description = '기업·기관의 행사와 이벤트를 기획·준비·진행하는 전문가' WHERE name = '행사 운영자';
UPDATE jobs SET description = '고객 불만을 처리하고 만족도를 높이는 고객 서비스 전문가' WHERE name = '고객 만족 전문가(CS)';
UPDATE jobs SET description = '제품의 보관·운송·배송 과정을 총괄 관리하는 전문가' WHERE name = '물류 관리자';
UPDATE jobs SET description = '공장·제조 현장의 생산 효율과 품질을 총괄 관리하는 전문가' WHERE name = '생산 관리자';
UPDATE jobs SET description = '상품이 생산자에서 소비자에게 전달되는 유통 경로를 관리하는 전문가' WHERE name = '유통 관리사';
UPDATE jobs SET description = '건물·주택·상업용 부동산의 운영과 관리를 담당하는 전문가' WHERE name = '부동산 관리사';
UPDATE jobs SET description = '건물·설비의 유지보수와 안전을 책임지는 시설 전문가' WHERE name = '시설 관리 전문가';
UPDATE jobs SET description = '개인·기업의 금융 자산 운용과 투자 계획을 지원하는 전문가' WHERE name = '자산 관리사';
UPDATE jobs SET description = '병원·의료기관의 행정·운영·경영을 담당하는 전문가' WHERE name = '의료 행정가';
UPDATE jobs SET description = '시설·사람·재산을 위협으로부터 보호하는 경비 전문가' WHERE name = '보안 요원';
UPDATE jobs SET description = '산업·건설 현장의 재해를 예방하고 안전 교육을 담당하는 전문가' WHERE name = '안전 관리자';
UPDATE jobs SET description = '자연재해·사고 발생 시 피해자 구호 및 복구를 지원하는 전문가' WHERE name = '재난 구호 전문가';
UPDATE jobs SET description = '환경 법규 위반을 단속하고 환경 오염을 감시하는 공무원' WHERE name = '환경 감시원';
UPDATE jobs SET description = '문화재의 보존 처리·복원·관리를 담당하는 전문가' WHERE name = '문화재 보존원';
UPDATE jobs SET description = '박물관·미술관의 소장품을 관리하고 전시를 기획하는 전문가' WHERE name = '박물관 학예사';
UPDATE jobs SET description = '역사적으로 중요한 문서·자료를 보존·복원하는 전문가' WHERE name = '기록물 보존가';
UPDATE jobs SET description = '공공·학교 도서관의 서비스와 운영을 책임지는 관리 전문가' WHERE name = '도서관 운영자';
UPDATE jobs SET description = '기업의 사회적 책임 활동을 기획하고 실행하는 전문가' WHERE name = 'CSR 담당자';
UPDATE jobs SET description = '지역 주민의 자치 역량을 강화하고 공동체를 활성화하는 전문가' WHERE name = '마을 공동체 활동가';
UPDATE jobs SET description = '소비자 생활협동조합의 운영과 관리를 담당하는 전문가' WHERE name = '생협 운영자';
UPDATE jobs SET description = '복지 서비스와 지역 자원을 연계해 위기 가구를 지원하는 전문가' WHERE name = '사회 안전망 코디네이터';
UPDATE jobs SET description = '요양원·장애인 시설 등의 운영을 책임지는 관리자' WHERE name = '복지 시설 관리자';
UPDATE jobs SET description = '지역의 경제·문화·복지 발전을 위한 사업을 기획·실행하는 전문가' WHERE name = '지역사회 발전 매니저';
UPDATE jobs SET description = '새로운 아이디어로 사업을 시작하고 기업을 성장시키는 창업 리더' WHERE name = '창업가(CEO)';
UPDATE jobs SET description = '영화·드라마·방송 프로젝트의 전체 제작을 총괄하는 프로덕션 리더' WHERE name = '총괄 프로듀서(PD)';
UPDATE jobs SET description = '브랜드·광고·미디어의 창의적 방향성을 총괄하는 크리에이티브 리더' WHERE name = '크리에이티브 디렉터';
UPDATE jobs SET description = '디지털 서비스의 기능·경험·비즈니스 모델을 설계하는 전문가' WHERE name = '서비스 기획자';
UPDATE jobs SET description = '사회 문제를 새로운 방식으로 해결하는 혁신적 활동가·기업가' WHERE name = '사회 혁신가';
UPDATE jobs SET description = '브랜드 포지셔닝과 장기 전략을 수립하는 마케팅 전문가' WHERE name = '브랜드 전략가';
UPDATE jobs SET description = '교육과 기술을 결합한 학습 플랫폼·도구를 개발하는 전문가' WHERE name = '에듀테크 개발자';
UPDATE jobs SET description = '복잡한 과학을 일반 대중이 쉽게 이해할 수 있도록 전달하는 전문가' WHERE name = '과학 커뮤니케이터';
UPDATE jobs SET description = '사회 문제를 해결하기 위한 법·제도·정책을 설계하는 전문가' WHERE name = '정책 입안자';
UPDATE jobs SET description = '노후 도시 지역을 새로운 방식으로 재활성화하는 전문가' WHERE name = '도시 재생 전문가';
UPDATE jobs SET description = '다양한 문화권의 생활 방식과 가치관을 연구하는 인문학자' WHERE name = '문화 인류학자';
UPDATE jobs SET description = '기술이 인간·사회·문화에 미치는 영향을 연구하는 학제간 학자' WHERE name = '기술 인문학자';
UPDATE jobs SET description = '비정부 공익 단체를 이끌며 사회 변화를 추진하는 리더' WHERE name = 'NGO 단체장';
UPDATE jobs SET description = '기술과 예술을 결합해 관객과 상호작용하는 작품을 창작하는 예술가' WHERE name = '인터랙티브 아티스트';
UPDATE jobs SET description = '앱·웹 서비스의 버튼·안내 문구 등 언어를 설계하는 전문가' WHERE name = 'UX 라이터';
UPDATE jobs SET description = '기업의 해외 진출 전략과 글로벌 운영을 자문하는 전문가' WHERE name = '글로벌 비즈니스 컨설턴트';
UPDATE jobs SET description = '현실에 기반한 다큐멘터리 영화를 기획·촬영·편집하는 감독' WHERE name = '다큐멘터리 감독';
UPDATE jobs SET description = '조직과 사회에 근본적인 변화를 이끄는 비전 제시형 경영자' WHERE name = '변혁적 리더';
UPDATE jobs SET description = '여러 예술 장르를 넘나들며 통합적인 작품을 창작하는 예술가' WHERE name = '종합 예술가';
